# Generated by Django 4.2.4 on 2023-08-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_name',
            new_name='category',
        ),
    ]
